version: 'Compose specification'
services:
  election:
    restart: always
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: